spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/biblioteca?useTimezone=true&serverTimezone=UTC
    username: root  jpa:    hibernate:      ddl-auto: update
server:  servlet:    context-path: /biblioteca